name: Build and Publish C#

on:
  workflow_dispatch:

jobs:
  build_and_publish_csharp:
    runs-on: ubuntu-latest
    env:
      NUGET_TOKEN: ${{ secrets.NUGET_UPLOAD_KEY }}
      PROJECT_NAME: Jay.Serialization

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Build
        run: |
          echo "Building .NET project"
          dotnet build -c Release "./Src/Jay.Serialization/${{ env.PROJECT_NAME }}.csproj"

      - name: Publish to NuGet
        run: |
          echo "Publishing to NuGet"
          dotnet pack -c Release "./Src/Jay.Serialization/${{ env.PROJECT_NAME }}.csproj"
          dotnet nuget push ./${{ env.PROJECT_NAME }}/bin/Release/${{ env.PROJECT_NAME }}.*.nupkg --source https://api.nuget.org/v3/index.json --api-key $NUGET_TOKEN
